# Generated by Django 6.0.3 on 2026-03-25 19:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Routine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("afternoon", "Afternoon"),
                            ("evening", "Evening"),
                        ],
                        default="morning",
                        max_length=10,
                    ),
                ),
                (
                    "days",
                    models.CharField(
                        default="mon,tue,wed,thu,fri,sat,sun",
                        help_text="Comma-separated day codes: mon,tue,wed,thu,fri,sat,sun",
                        max_length=27,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order within slot on the dashboard.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Routine",
                "verbose_name_plural": "Routines",
                "ordering": ["slot", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="RoutineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("body", "Body"),
                            ("self_care", "Self-Care"),
                            ("hygiene", "Hygiene"),
                            ("food", "Food / Meals"),
                            ("work", "Work"),
                            ("code", "Code / Career"),
                            ("cleaning", "Cleaning / Maintenance"),
                            ("pet", "Pet"),
                            ("bedtime", "Bedtime"),
                            ("wakeup", "Wake Up"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="routines.routine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Routine Item",
                "verbose_name_plural": "Routine Items",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="RoutineCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_on", models.DateField(default=datetime.date.today)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="routines.routineitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Routine Completion",
                "verbose_name_plural": "Routine Completions",
                "ordering": ["-completed_on"],
                "unique_together": {("item", "completed_on")},
            },
        ),
    ]
