# Generated by Django 6.0.3 on 2026-03-25 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="routine",
            old_name="active",
            new_name="is_active",
        ),
    ]
