# Generated by Django 6.0.3 on 2026-04-22 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0002_rename_active_routine_is_active"),
        ("routines", "0003_routine_session"),
    ]

    operations = []
