# Generated by Django 6.0.3 on 2026-04-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0004_merge_20260422_1117"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routine",
            name="reset_mode",
            field=models.CharField(
                choices=[
                    ("daily", "Daily (resets each night)"),
                    ("on_complete", "On Completion (stays open until all items done)"),
                ],
                default="daily",
                help_text="Daily: progress resets each night. On Completion: routine stays open on the dashboard until every item is checked off. ",
                max_length=15,
            ),
        ),
    ]
