# Generated by Django 6.0.3 on 2026-03-25 19:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("therapy", "Therapy"),
                            ("work", "Work"),
                            ("career", "Career"),
                            ("personal", "Personal"),
                            ("routine", "Routine"),
                            ("finance", "Finance"),
                            ("health", "Health"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=15,
                    ),
                ),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "due_date",
                    models.DateField(
                        blank=True, help_text="Target completion date", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to move a goal to the back-burner without deleting.",
                    ),
                ),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "last_progress",
                    models.DateField(
                        blank=True,
                        help_text="Date of the most recent GoalItem completion.Auto-updated via post_save signal.",
                        null=True,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Goal",
                "verbose_name_plural": "Goals",
                "ordering": ["-priority", "due_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="GoalItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("task", "Task"),
                            ("milestone", "Milestone"),
                            ("blocking", "Blocking Task"),
                        ],
                        default="task",
                        max_length=10,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=15,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to move item to back burner without deleting.",
                    ),
                ),
                ("is_complete", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="goals.goal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Goal Item",
                "verbose_name_plural": "Goal Items",
                "ordering": ["order", "due_date", "name"],
            },
        ),
    ]
