# Generated by Django 6.0.3 on 2026-04-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="last_progress",
            field=models.DateField(
                blank=True,
                help_text="Date of the most recent GoalItem completion.Auto-updated inside mark_complete().",
                null=True,
            ),
        ),
    ]
