# Generated by Django 6.0.3 on 2026-03-25 19:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("goals", "0001_initial"),
        ("habits", "0001_initial"),
        ("routines", "0001_initial"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("in_app", "In-App"),
                            ("sms", "SMS (Twilio)"),
                            ("push", "Push Notification"),
                        ],
                        default="in_app",
                        max_length=10,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("once", "One-time"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("custom", "Custom Interval"),
                        ],
                        default="once",
                        max_length=10,
                    ),
                ),
                (
                    "interval",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Every N units (e.g. interval=2 + frequency=weekly → every 2 weeks)",
                    ),
                ),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "goal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="goals.goal",
                    ),
                ),
                (
                    "habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="habits.habit",
                    ),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="routines.routine",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reminder",
                "verbose_name_plural": "Reminders",
                "ordering": ["next_run"],
            },
        ),
    ]
