# Generated by Django 6.0.3 on 2026-03-25 19:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("self_improvement", "Self-Improvement"),
                            ("health", "Health"),
                            ("spending", "Spending / Financial"),
                            ("mental", "Mental"),
                            ("physical", "Physical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[("yn", "Yes / No"), ("scale", "Scale (1-10)")],
                        default="yn",
                        max_length=5,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("custom", "Custom"),
                        ],
                        default="daily",
                        max_length=15,
                    ),
                ),
                ("start_date", models.DateField(default=datetime.date.today)),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank for an ongoing habit.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order on the dashboard habit grid.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Habit",
                "verbose_name_plural": "Habits",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="HabitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logged_on", models.DateField(default=datetime.date.today)),
                (
                    "yn_value",
                    models.BooleanField(
                        blank=True,
                        help_text="Set for yes/no habits. True = done, False = not done.",
                        null=True,
                    ),
                ),
                (
                    "scale_value",
                    models.IntegerField(
                        blank=True,
                        help_text="Set for scale habits. Integer 1-10.",
                        null=True,
                    ),
                ),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="habits.habit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Habit Log",
                "verbose_name_plural": "Habit Logs",
                "ordering": ["-logged_on"],
                "unique_together": {("habit", "logged_on")},
            },
        ),
    ]
