# Generated by Django 6.0.3 on 2026-03-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To Do"),
                            ("in_progress", "In Progress"),
                            ("stalled", "Stalled"),
                            ("complete", "Complete"),
                        ],
                        default="todo",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("household", "Household"),
                            ("adulting", "Adulting"),
                            ("admin", "Admin"),
                            ("therapy", "Therapy"),
                            ("career", "Career"),
                            ("personal", "Personal"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "energy_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mental", "Mental"),
                            ("physical", "Physical"),
                            ("social", "Social"),
                        ],
                        help_text="What kind of energy does this task require?",
                        max_length=15,
                    ),
                ),
                (
                    "where_task",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("home", "Home"),
                            ("outdoors", "Outdoors"),
                            ("out_and_about", "Out and About"),
                        ],
                        help_text="Where does this task need to happen?",
                        max_length=15,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Uncheck to archive without deleting."
                    ),
                ),
                ("is_complete", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "ordering": ["is_complete", "due_date", "-priority"],
            },
        ),
    ]
